version: '3.9'
services:
  music-service:
    image: music_image
    container_name: music-service
    build: BEJ_C2_S3_REST_API_MONGODB_MC_1/
    restart: always
    networks:
      - mynetwork
    ports:
      - 8091:8091
    depends_on:
      - mongoservice
      - cloudapiservice


  mongoservice:
    image: mongo
    container_name: mongoservice
    ports:
      - 27017:27017
    networks:
      - mynetwork

  authentication-service:
    image: authentication_image
    container_name: authentication-service
    build: UserAuthentication/
    restart: always
    networks:
      - mynetwork
    ports:
      - 8082:8082
    depends_on:
      - mysqlservice
      - cloudapiservice

  mysqlservice:
    image: mysql:latest
    container_name: mysqlservice
    networks:
      - mynetwork
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  cloudapiservice:
    image: apigateway-service
    build: SpringCloudAPIGateway/
    restart: always
    networks:
      - mynetwork
    ports:
      - 9007:9007



networks:
  mynetwork:
    driver: bridge
